// <auto-generated />
using System;
using AyodhyaYatra.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AyodhyaYatra.API.Migrations
{
    [DbContext(typeof(AyodhyaYatraContext))]
    partial class AyodhyaYatraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AyodhyaYatra.API.Models.AudioGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AudioGallery");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.ImageStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioGalleryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MasterDataId")
                        .HasColumnType("int");

                    b.Property<int?>("MasterPadavId")
                        .HasColumnType("int");

                    b.Property<int?>("MasterYatraId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewsUpdateId")
                        .HasColumnType("int");

                    b.Property<int?>("PhotoAlbumId")
                        .HasColumnType("int");

                    b.Property<int?>("PhotoGalleryId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TempleId")
                        .HasColumnType("int");

                    b.Property<int?>("ThreeSixtyDegreeGalleryId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<int?>("VideoGalleryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AudioGalleryId");

                    b.HasIndex("MasterDataId");

                    b.HasIndex("MasterPadavId");

                    b.HasIndex("MasterYatraId");

                    b.HasIndex("NewsUpdateId");

                    b.HasIndex("PhotoAlbumId");

                    b.HasIndex("PhotoGalleryId");

                    b.HasIndex("TempleId");

                    b.HasIndex("ThreeSixtyDegreeGalleryId");

                    b.HasIndex("VideoGalleryId");

                    b.ToTable("ImageStores");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasterDataType")
                        .HasColumnType("int");

                    b.Property<string>("TaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VideoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterDatas");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MasterDivisions");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterPadav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("YatraId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YatraId");

                    b.ToTable("MasterPadavs");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterYatra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentYatraId")
                        .HasColumnType("int");

                    b.Property<string>("TaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentYatraId");

                    b.ToTable("MasterYatras");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.NewsUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MasterDataType")
                        .HasColumnType("int");

                    b.Property<int>("NewsUpdateType")
                        .HasColumnType("int");

                    b.Property<string>("TaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("WebUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsUpdates");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.PhotoAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhotoAlbum");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.PhotoGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PhotoAlbumId")
                        .HasColumnType("int");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhotoAlbumId");

                    b.ToTable("PhotoGallery");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.Temple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PadavId")
                        .HasColumnType("int");

                    b.Property<string>("SequenceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temple360DegreeVideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempleBarcodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TempleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TempleURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<string>("VideoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YatraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PadavId");

                    b.HasIndex("YatraId");

                    b.ToTable("Temples");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.TempleSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SequenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TempleSequences");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.ThreeSixtyDegreeGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThreeSixtyDegreeGallery");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerificationCodeExpireOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResetCodeInitiated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTcAccepted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordResetCodeExpireOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.VideoGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGallery");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.ImageStore", b =>
                {
                    b.HasOne("AyodhyaYatra.API.Models.AudioGallery", null)
                        .WithMany("Images")
                        .HasForeignKey("AudioGalleryId");

                    b.HasOne("AyodhyaYatra.API.Models.MasterData", null)
                        .WithMany("Images")
                        .HasForeignKey("MasterDataId");

                    b.HasOne("AyodhyaYatra.API.Models.MasterPadav", null)
                        .WithMany("Images")
                        .HasForeignKey("MasterPadavId");

                    b.HasOne("AyodhyaYatra.API.Models.MasterYatra", null)
                        .WithMany("Images")
                        .HasForeignKey("MasterYatraId");

                    b.HasOne("AyodhyaYatra.API.Models.NewsUpdate", null)
                        .WithMany("Images")
                        .HasForeignKey("NewsUpdateId");

                    b.HasOne("AyodhyaYatra.API.Models.PhotoAlbum", null)
                        .WithMany("Images")
                        .HasForeignKey("PhotoAlbumId");

                    b.HasOne("AyodhyaYatra.API.Models.PhotoGallery", null)
                        .WithMany("Images")
                        .HasForeignKey("PhotoGalleryId");

                    b.HasOne("AyodhyaYatra.API.Models.Temple", null)
                        .WithMany("Images")
                        .HasForeignKey("TempleId");

                    b.HasOne("AyodhyaYatra.API.Models.ThreeSixtyDegreeGallery", null)
                        .WithMany("Images")
                        .HasForeignKey("ThreeSixtyDegreeGalleryId");

                    b.HasOne("AyodhyaYatra.API.Models.VideoGallery", null)
                        .WithMany("Images")
                        .HasForeignKey("VideoGalleryId");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterPadav", b =>
                {
                    b.HasOne("AyodhyaYatra.API.Models.MasterYatra", "Yatra")
                        .WithMany()
                        .HasForeignKey("YatraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yatra");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterYatra", b =>
                {
                    b.HasOne("AyodhyaYatra.API.Models.MasterYatra", "ParentYatra")
                        .WithMany()
                        .HasForeignKey("ParentYatraId");

                    b.Navigation("ParentYatra");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.PhotoGallery", b =>
                {
                    b.HasOne("AyodhyaYatra.API.Models.PhotoAlbum", "PhotoAlbum")
                        .WithMany()
                        .HasForeignKey("PhotoAlbumId");

                    b.Navigation("PhotoAlbum");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.Temple", b =>
                {
                    b.HasOne("AyodhyaYatra.API.Models.MasterPadav", "Padav")
                        .WithMany()
                        .HasForeignKey("PadavId");

                    b.HasOne("AyodhyaYatra.API.Models.MasterYatra", "Yatra")
                        .WithMany("Temples")
                        .HasForeignKey("YatraId");

                    b.Navigation("Padav");

                    b.Navigation("Yatra");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.AudioGallery", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterData", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterPadav", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.MasterYatra", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Temples");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.NewsUpdate", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.PhotoAlbum", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.PhotoGallery", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.Temple", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.ThreeSixtyDegreeGallery", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AyodhyaYatra.API.Models.VideoGallery", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
